# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Mohammad Norouzzadegan
title: DevOps Eng
email: Norouzzadegan@gmail.com
# email_title: Email (Email title override)
website: https://Norouzzadegan.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  Norouzzadegan
stackoverflow_username: "13566519"
linkedin_username: Norouzzadegan

# Additional icon links
additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: /images/telegram.svg
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
gtm: "GTM-0000000"
gtag: "UA-00000000-0"
google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /images/norouzzadegan.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Mohammad Norouzzadegan. I am a <mark>DevOps engineer</mark>. In addition to devops, I also study <mark>Security</mark> and <mark>DevSecOps</mark> issues. I like to try challenging environments.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Mahsan
        sub_title: DevOps Eng
        caption: May 2020 - present
        link: mahsan.co
        quote: Provider of products and solutions for the new world of communication.
        description: | # this will include new lines to allow paragraphs
          - Automatic Authentication and Autorization Jenkins-Python-ActiveDirectory
          - Develop Naser project to automate process need to be automate
          - Administrator of Jenkins as Continues delivery
          - administrator of AzureDevps as SCM(Source Control Management)
          - Implement servecis on docker
          - Implement of infrustructure for a product of company smoke test.
      - layout: left
        title: SINA Innovative Communications System Co
        sub_title: Test & Implementation Telecom Core Network on docker
        caption: July 2019 - March 2020
        link: sinacomsys.com
        quote: As a knowledge-based company at SINA Co.
        description: | # this will include new lines to allow paragraphs
          - Implementation Gitlab docker based on Linux Ubuntu and Coreos
          - Implementation Sina IMS Core
          - Testing and Evaluation KPI of Sina IMS Core with SIPp and MTS
          - Survey of Authentication in IMS network with AKAv1 AKAv2 protocol
      - layout: left
        title: Nima Research Lab
        sub_title: Vulnerability Assessment & Penetration Testing
        caption: November 2017 - September 2018
        description: | # this will include new lines to allow paragraphs
          - Scan and Explore vulnerability on Web application
          - Explore of internal network from vulnerability

  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
     ## Experienced
      - Operation system: Ubuntu, Debian
      - Programing Language: Python, BashScript
      - Continues Integration: Jenkins, Gitlab CI, Github Action
      - Container Runtime: Docker
      - GIT Source Control Management: AzureDevOps, Gitlab, Github
      - Infrastructure as code: Terraform
      - Voip: Sip, SiPp, IMS, Mts Ericson
      - Virtualization: Vsphere
      - Penteration Testing: Nessus, Acunetix, Metasploit, Burp Suite

     ## Familiar
      - Configuration Management: Ansible
      - Monitoring: Prometheus-Grafana
      - Orchestration: Kubernetes
    

  - title: Education
    layout: list
    content:
      - layout: top-middle
        title:  K. N. Toosi University of Technology
        sub_title: Master Telecommunication Eng
        caption: 2013 - 2016
        link: kntu.ac.ir
      - layout: top-middle
        title:  Shahrood University of Technology
        sub_title: Bachelor Electrical 
        caption: 2009 - 2012 Eng
        link: shahroodut.ac.ir

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        # border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        # title: 
        link: civilica.com/doc/941987/
        # link_text: Link Text
        caption: Aug 2019
        # quote: >
#           Assessing Derived Attacks from MITM Attack in Industrial Control Systems with Respect to DNP3 Protocol
        description: | # this will include new lines to allow paragraphs
          ## Assessing Derived Attacks from MITM Attack in Industrial Control Systems with Respect to DNP3 Protocol

          International ISC Conference on Information Security and Cryptology

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
